- hosts: fortigate01
  gather_facts: false
  tasks:
   - name: Get Config Elements
     ansible.netcommon.cli_command:
       command: show system global
     register: output

   - name: print output
     debug:
       var: output.stdout_lines
